### PR TITLE
Docker container for Qibo

### PR DESCRIPTION
**Pull request by JavierSerranoGarcia**
This initial container should allow us to assess the utility  of containers in the Qibo project

### CODE REVIEW

**Comment by JavierSerranoGarcia** [comment]
At this point of the project I think there is no need for a docker container in order to distribute Qibo, the pip install is more suitable for the sort of developer who can be interested in trying it.
In the future if we want to deploy it in the cloud there will be a real necessity for docker container but then we will decide the container that will be needed.
So, I propose  just to close this PR.

**Comment by scarrazza** [comment]
@JavierSerranoGarcia I think the docker image is a good idea. 

Let me propose the following instead of closing this PR:
- could you please check the current files in this PR, and make sure everything is consistent (I see 114 changed files)
- we have to test the performance of this PR

If you take care of the first point, I can take care of the second point.

**Comment by JavierSerranoGarcia** [comment]
OK @scarrazza, let me redo the container with the last version of Qibo

**Comment by JavierSerranoGarcia** [comment]
OK @scarrazza, let me redo the container with the last version of Qibo

**Comment by JavierSerranoGarcia** [comment]
Hi @scarrazza 
I have built a new docker container with the last qibo version. I uploaded it to Docker Hub. I have given it public access now it has been released. But it is still the issue I am using a personal account in Docker Hub. I am expecting some suggestion from you ...

Regarding the performance I did a simple test running an script and the docker was twice slower (see the elapsed time)

In the docker container
```
root@f685503d4337:/usr/src/app# cd examples/qiboGrover3satBench/
root@f685503d4337:/usr/src/app/examples/qiboGrover3satBench# python main.py --file='data/12bit/n12i1.txt'
Solution: 010100110001
10 clause of 3 boolean variables out of 12, (v1,v2,...vn), (1=T, 0=F): [' 4 6 9\n', ' 6 7 11\n', ' 5 7 9\n', ' 3 5 8\n', ' 1 3 7\n', ' 1 7 10\n', ' 8 9 11\n', ' 7 9 10\n', ' 1 11 12\n', ' 2 6 9\n']
Number of Grover operators R= 50
Elapsed time:  37.728591482999036
Sampled results:
Counter({'010100110001': 1})
Most common bitstring: 010100110001
Found a match: True
```

Executing it directly in my machine
```
(qibo) javi@Mini-HP-WS:~/OneDrive/pythonDev/quantum/qiboGrover$ python main.py --file='data/12bit/n12i1.txt'
Solution: 010100110001
10 clause of 3 boolean variables out of 12, (v1,v2,...vn), (1=T, 0=F): [' 4 6 9\n', ' 6 7 11\n', ' 5 7 9\n', ' 3 5 8\n', ' 1 3 7\n', ' 1 7 10\n', ' 8 9 11\n', ' 7 9 10\n', ' 1 11 12\n', ' 2 6 9\n']
Number of Grover operators R= 50
Elapsed time:  16.19315699400613
Sampled results:
Counter({'010100110001': 1})
Most common bitstring: 010100110001
Found a match: True
```


`

**Comment by JavierSerranoGarcia** [comment]
I realized that the comparison was or fair because the docker container was not using the GPU. When I execute the script in my computer without the GPU, it takes more time than the container. It is quite weird and more tests should be done.

```
(qibo) javi@Mini-HP-WS:~/OneDrive/pythonDev/quantum/qiboGrover$ python main.py --file='data/12bit/n12i1.txt'
Solution: 010100110001
10 clause of 3 boolean variables out of 12, (v1,v2,...vn), (1=T, 0=F): [' 4 6 9\n', ' 6 7 11\n', ' 5 7 9\n', ' 3 5 8\n', ' 1 3 7\n', ' 1 7 10\n', ' 8 9 11\n', ' 7 9 10\n', ' 1 11 12\n', ' 2 6 9\n']
Number of Grover operators R= 50
Elapsed time:  40.5712727830105
Sampled results:
Counter({'010100110001': 1})
Most common bitstring: 010100110001
Found a match: True
```

**Comment by scarrazza** [comment]
Ok, thanks, let us know if you find the problem.

**Comment by JavierSerranoGarcia** [comment]
I found the problem. I was not using the qibo last version ....

Now the execution time in my machine  is a bit faster than the container 36.2 vs 37.7

`(qibo_0.1.0) javi@Mini-HP-WS:~/OneDrive/pythonDev/quantum/qiboGrover$ python main.py --file='data/12bit/n12i1.txt'

Solution: 010100110001

10 clause of 3 boolean variables out of 12, (v1,v2,...vn), (1=T, 0=F): [' 4 6 9\n', ' 6 7 11\n', ' 5 7 9\n', ' 3 5 8\n', ' 1 3 7\n', ' 1 7 10\n', ' 8 9 11\n', ' 7 9 10\n', ' 1 11 12\n', ' 2 6 9\n']

Number of Grover operators R= 50

Elapsed time:  **36.235569034994114**

Sampled results:

Counter({'010100110001': 1})

Most common bitstring: 010100110001

Found a match: True
`

**Comment by scarrazza** [comment]
Great, please cleanup this PR or create a new one with documentation for GPU.

**Comment by JavierSerranoGarcia** [comment]
Hi @scarrazza, the docker container is not using the GPU and I do not see what the problem is. Maybe we can close this PR and later we will solve the issue of the containers and the GPUs. What do you think?

**Comment by scarrazza** [comment]
Ok, please go ahead.

**Pull request closed without merging**
