### PR TITLE
changing documentation urls from latest to stable

### LINKED ISSUE #246: Adjust docs urls
Before releasing 0.1.1 we should update all urls to point to the stable readthedocs pages.

### PR DESCRIPTION
**Pull request by scarrazza**
Closes #246.

### CODE REVIEW

**Review by stavros11 — APPROVED** [review]
Thanks for the update and the typo fixes. I could not find any other "latest" references in our docs. 

Just two questions:
* The documentation badge in ` README.md` is still using the latest. Is this what we want?
* When accessing the `https://qibo.readthedocs.io/` webpage without specifying latest or stable I am automatically redirected to latest. Is there a way to switch that to stable?

**Comment by scarrazza** [comment]
> The documentation badge in README.md is still using the latest. Is this what we want?

yes, because we can quickly see if there troubles with the latest master documentation creation.

> When accessing the https://qibo.readthedocs.io/ webpage without specifying latest or stable I am automatically redirected to latest. Is there a way to switch that to stable?

yes, I will change the default behaviour of readthedocs to show stable instead of latest by default.

**Comment by stavros11** [comment]
Just a reminder that in #238 @DiegoGM91 checked the how-to examples in our documentation up to the QAOA section. Shall I make a pass over the remaining sections before the v0.1.1 release or has this already been done?

**Comment by scarrazza** [comment]
Yes, please, that's a good point.

**Pull request merged**
