### PR TITLE
documentation instructions

### PR DESCRIPTION
**Pull request by scarrazza**
This PR includes a new section in the docs explaining how to compile locally and extend it.

### CODE REVIEW

**Comment by AdrianPerezSalinas** [comment]
I see this documentation on the documentation pretty nice. However, there is something that I cannot figure out. When I am compiling the documentation, I get this error message:

`qibo/doc/source/applications.rst:8: WARNING: toctree contains reference to document 'tutorials/aavqe/README' that doesn't have a title: no link will be generated`

That happens with all the different tutorials. I have been comparing my code to the stable one in qibo.readthedocs but I cannot see any difference, so I am not sure about what is going on here. Do we have to add a title for the `README.md` files or there is any other way to compile everything?

**Comment by scarrazza** [comment]
Yeah, because we mixing rst with markdown, but as far it renders the text properly we can ignore this warning.

**Comment by AdrianPerezSalinas** [comment]
The point is that I cannot access to the documentation files, this is all I got
image

**Comment by scarrazza** [comment]
I don't get this issue, maybe you have an outdated version of sphinx? Probably the best is to reinstall these packages:
```python
"docs": ["sphinx", "sphinx_rtd_theme", "recommonmark", "sphinxcontrib-bibtex", "sphinx_markdown_tables", "nbsphinx", "IPython"],
```

**Comment by AdrianPerezSalinas** [comment]
I have done it already, but the problem persists. 
If you can compile it and there is no problem, we can just merge it, I find it alright

**Comment by scarrazza** [comment]
@stavros11 could you please have a quick check? The procedure works for me.

**Review by stavros11 — APPROVED** [review]
> @stavros11 could you please have a quick check? The procedure works for me.

I just checked and I can compile the docs normally from this branch using `make html`. I also tried completely remove the `build` folder and compiling from scratch and it works. I am not sure what is the problem Adrian is getting.

Also the new section looks fine.

**Comment by scarrazza** [comment]
Ok, thanks, lets merge and then discuss with @AdrianPerezSalinas privately.

**Pull request merged**
