### PR TITLE
refactoring for qibotf

### PR DESCRIPTION
**Pull request by scarrazza**
Small adjustments to interface with qibotf.

### CODE REVIEW

**Comment by scarrazza** [comment]
@stavros11 we have some pylint import errors for windows. I think we can disable this check for the specific files given that we are not importing these libraries, except for the matrices.py import.

**Review by stavros11 — APPROVED** [review]
Thanks for the update, this looks good to merge.

> @stavros11 we have some pylint import errors for windows. I think we can disable this check for the specific files given that we are not importing these libraries, except for the matrices.py import.

I think that #402 fixes the matrices.py import issue. For the rest tensorflow imports I believe it should be fine to just do `# pylint: disable`. I am not sure if there is a better solution.

**Comment by scarrazza** [comment]
@stavros11 thanks, I will merge #402 as soon as test finish, and then fix this PR so we can continue in your #398.

**Comment by scarrazza** [comment]
@stavros11 #402 helps but there are several tests relying on `.numpy`, we should probably have a `to_numpy` method in the abstract backend to avoid casting with `K.qnp.dtypes` everywhere.

**Pull request merged**
